services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/radicle/app
      - ./config/php.ini:/usr/local/etc/php/conf.d/radicle.ini
    networks:
      - radicle
    depends_on:
      database:
        condition: service_healthy
    environment:
      WP_CLI_ALLOW_ROOT: 1

  web:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ..:/radicle/app:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - radicle

  database:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - radicle
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10

networks:
  radicle:
    driver: bridge